# Generated by Django 3.0.6 on 2020-05-26 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200526_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='emailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
