# Generated by Django 3.0.6 on 2020-06-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20200601_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='empId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Account', to_field='empId'),
        ),
    ]
