# Generated by Django 3.0.7 on 2020-06-29 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200601_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_start', models.TimeField()),
                ('check_in_end', models.TimeField()),
                ('check_out_start', models.TimeField()),
                ('check_out_end', models.TimeField()),
                ('orgId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Organization')),
            ],
        ),
    ]
