# Generated by Django 3.0.7 on 2020-08-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('last4', models.CharField(max_length=4)),
                ('network', models.CharField(max_length=20)),
                ('typeOfCard', models.CharField(max_length=10)),
                ('issuer', models.CharField(max_length=20)),
                ('international', models.BooleanField(default=False)),
                ('emi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payId', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=5)),
                ('method', models.CharField(max_length=20)),
                ('captured', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('createdAt', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
